### ISSUE TITLE
Be able to point to sosreport directly

### ISSUE THREAD

**Issue by jskacel** [lucas-benedito/sos-ansible#19]
Would be nice to have feature that I point to sosreport directly, eg.:

`python sos-ansible/main.py sosreport-server1-0123456-hellyea`

in case of more sosreports:
`python sos-ansible/main.py sosreport-server1-0123456-hellyea sosreport-server2-0123456-rofl sosreport-server3-0123456-copter`

And if there will be possibility to use directly .tar.gz, so it automagically extract it.. that would be amazing :)

**Comment by lucas-benedito** [comment]
Currently, we introspect all subdirectories from sos_directory and provide a summary for each containing a valid sosreport inside.
Implementing the possibility to read a unique sosreport might be doable but changes the logic behind it drastically.
I think this might be doable, but, at a later stage.

**Comment by lucas-benedito** [comment]
feature implemented and tested. 
Closing issue.
