### ISSUE TITLE
Configurable paths are breaking with "~" unix statement

### ISSUE THREAD

**Issue by lucas-benedito** [lucas-benedito/sos-ansible#25]
Based on feedback, using unexpanded "~" for home folder breaks the customizable paths for the tool. 

os.path.expanduser can be used to handle it

**Comment by lucas-benedito** [comment]
@jskacel can you please check if the PR linked resolves the behavior mentioned?

**Comment by jskacel** [comment]
Tested, working well.

**Comment by lucas-benedito** [comment]
@jskacel Thank you for the report and testing!
