### ISSUE TITLE
sos_ansible -t requires case number

### ISSUE THREAD

**Issue by jskacel** [lucas-benedito/sos-ansible#42]
If case number is in sosreport, it should be able to get it from it

**Comment by lucas-benedito** [comment]
As the case number added to the sosreport filename is an optional feature from sos command, the benefit vs effort to implement this feature is likely not worth it. As more users get hands on experience, we may discuss this idea further.
Also, the sosreport filename can be non-standard in many cases, adding complexity to this feature.
For now I am closing this issue as wontfix but it may be reopened if we see fit.

**Comment by jskacel** [comment]
`/-(\d{8})-/` is what we looking for.. if this regexp return something, then we can use it as case number.. if not, error should be thrown
