### ISSUE TITLE
sos_ansible -c do not create directory

### ISSUE THREAD

**Issue by jskacel** [lucas-benedito/sos-ansible#43]
When running sos_ansible -c <number> -t <path_to_sosreport> it end up with error:
```
ERROR:Failure while creating ~/sosreports/results/<number> : [Errno 2] No such file or directory: '~/sosreports/results/<number>
```

If folder doesn't exists, it should be able to create it.

**Comment by jskacel** [comment]
My fault, folder `results` didnt exists in `~/sosreports/`.

**Comment by lucas-benedito** [comment]
I will keep this open just as a reminder for improving the error message.

**Comment by lucas-benedito** [comment]
The latest error message addresses the information about a missing parent directory.
https://github.com/lucas-benedito/sos-ansible/blob/devel/sos_ansible/modules/file_handling.py#L109
