### ISSUE TITLE
Set logger level to ERROR by default

### ISSUE THREAD

**Issue by lucas-benedito** [lucas-benedito/sos-ansible#50]
**Is your feature request related to a problem? Please describe.**
Currently the errors are only placed on the log file resulting in confusion when using the app

**Describe the solution you'd like**
Change the console log level to ERROR

**Comment by jskacel** [comment]
I think we would need to do review of logging first.. because some logs are strange, eg.:
```
2023-04-25 10:28:22,547 CRITICAL Validating sosreports at the source directory: /Users/jskacel/Downloads
2023-04-25 10:28:22,549 CRITICAL Processing node 192.168.100.10:
```

These should be INFO.

And then something like these should be CRITICAL and they should be printed to stdout:
```
2023-04-25 10:21:47,596 ERROR Unable to remove /Users/jskacel/Downloads/sosreports/results/0123456, Please remove before rerunning.
```

**Comment by lucas-benedito** [comment]
@jskacel Although the name CRITICAL sounds incorrect, this is the highest logging level in python without modifications
https://docs.python.org/3/library/logging.html#logging-levels
I did not want to create custom values and with that, used CRITICAL instead
