### ISSUE TITLE
add rules for database node

### ISSUE THREAD

**Issue by jbird2021** [lucas-benedito/sos-ansible#52]
**Is your feature request related to a problem? Please describe.**
Specifically taking a look at the following:
- server info <CPU, MEM, OS, packages, etc>
- /var/lib/pgsql/data/PG_VERSION
- /var/lib/pgsql/data/pg_hba.conf   <check host-based authentication is configured correctly>
- /var/lib/pgsql/data/postgresql.conf    <recommend comparing to a "default" installer template to only show diff>
- check if replication <select * from pg_stat_replication; unsure how to do this from the sosreport>
- /var/lib/pgsql/data/pg_log/
  - check logs for errors or unique messages

**Comment by lucas-benedito** [comment]
@jbird2021 can you check the PR linked if that helps with the PG needs?

For the `check if replication <select * from pg_stat_replication; unsure how to do this from the sosreport> `, we should work with the sosreport maintainers to check how to generate the PG data about replication.

**Comment by lucas-benedito** [comment]
@jbird2021 About the OS level info, a few were already present, but I've added some other rules.
