### ISSUE TITLE
Add check for Heartbeat skew

### ISSUE THREAD

**Issue by jskacel** [lucas-benedito/sos-ansible#54]
**Is your feature request related to a problem? Please describe.**
Add check for `Heartbeat skew` in logs, if that appears, time is not in sync across cluster

**Describe the solution you'd like**
Check `Heartbeat skew` in `/var/log/tower.log`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lucas-benedito** [comment]
https://github.com/lucas-benedito/sos-ansible/commit/057c969afe70555fedb0423a66eccb457d2446e3
