### ISSUE TITLE
Rules Processing can result in incorrect count

### ISSUE THREAD

**Issue by gamuniz** [lucas-benedito/sos-ansible#6]
consider the following rule:

{
     "Receptor": {
        "files": ["receptor.log", "receptor.fake"],
        "path": "var/log/receptor",
        "query": "error"
    }
}
even with results in receptor.log the count shows 0 as the match_count is inside the loop

**Comment by lucas-benedito** [comment]
@gamuniz i will test it further after today's PR merge. 
Wondering if I should still count the matches in this loop or by counting the output lines from tgt_directory.

**Comment by gamuniz** [comment]
I only found it because I was working on a helper script to create an ad-hoc rules/rules.json and was testing the results. I think both ways have merit but its really up to you.

**Comment by lucas-benedito** [comment]
Thanks @gamuniz! I created an issue to implement tests and will work on this in parallel.
As soon as I figure it out how to provide the detailed matches, they will define if I should count from the resulting files or during regex loop.

**Comment by gamuniz** [comment]
https://github.com/lucas-benedito/sos-ansible/pull/11

**Comment by lucas-benedito** [comment]
fixed by #3  and #20
